# Generated by Django 3.2 on 2023-02-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='logo_img',
            field=models.FileField(null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='members',
            name='server',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
