# Generated by Django 3.2 on 2023-02-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20230210_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='logo_img',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
