# Generated by Django 3.2 on 2023-03-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='access_apps',
            new_name='access_applications',
        ),
    ]
