# Generated by Django 3.2 on 2023-03-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_rename_access_apps_user_access_applications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
