# Generated by Django 3.2 on 2023-03-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
