# Generated by Django 3.2 on 2023-09-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='app_belongs',
            field=models.CharField(blank=True, choices=[('', 'Select Belongs'), ('mcs_global', 'MCS Global'), ('mcs_sl', 'MCS SL'), ('vvmarine', 'VVMARINE'), ('vvpaints', 'VVPAINTS'), ('vvsugars', 'VVSUGARS'), ('amt', 'AMT'), ('mcs', 'MCS'), ('ajax', 'Ajax'), ('vvgroups', 'VVGroups')], default='', max_length=20, null=True),
        ),
    ]
