version: '3'

services:
  web:
    image: saifclouddevops/msdjango
    restart: always
    ports:
      - "8000:8000"
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: djangocore
      POSTGRES_USER: salik
      POSTGRES_PASSWORD: salik
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: mdsaifsalik@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: salik
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

