# Generated by Django 3.2 on 2023-03-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
